[modo]
teste = false
email_teste = jlaguiarpinto@proton.me
email_secretaria = secretaria@atrpt.pt

[paths_dados]
#logo_jpg = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\imgs\logo.jpg
log_dir = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\logs
templates_dir = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\templates\email
template_enviofat = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\templates\email\Envio_Faturas.docx
email_logs = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\logs\email
atrpt_db = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\data\atrpt.db
rh_accdb = G:\.shortcut-targets-by-id\1NsBCziGNFjlQ-f8QRcezPsKVP9QzGdp0\APPs\atrpt\data\RH_ATRPT.accdb
# ==========================================================
# RAÍZES GOOGLE DRIVE
# ==========================================================
gdrive_secretaria = G:\.shortcut-targets-by-id\1Qr9fyP5j561vVIXw8b6mKJvgTyhTQF14\Secretaria
gdrive_csag = G:\.shortcut-targets-by-id\1YUU7cpAVBqQ-XmuiuqVAzKPjw-UZdVg8\CSAG
gdrive_associados = G:\.shortcut-targets-by-id\1U63DGZ6urrQl6543DNHJZQR93oRmv-G2\Associados
gdrive_aprovisionamento = G:\.shortcut-targets-by-id\1wt9AXRO3Hk4wBQv-tjY_Z8oHn1nR7ful\Servicos_Gerais
temp_dir = temp
users_db = data\atrpt.db
# ==========================================================
# SECRETARIA — MOVIMENTOS
# ==========================================================
secretaria_mov_dir = {gdrive_secretaria}\Movimentos
comprovativo_file = {secretaria_mov_dir}\comprovativo.csv
comprovativodd_file = {secretaria_mov_dir}\comprovativodd.csv
debitodireto_file = {secretaria_mov_dir}\debito_direto.txt
inflow_file = {secretaria_mov_dir}\inflow.xlsx
inflow_file_pq = {secretaria_mov_dir}\inflow.parquet
# ==========================================================
# CSAG — PIM
# ==========================================================
pim_dir = {gdrive_csag}\PIM
pim_file = {pim_dir}\Pim.xlsx
recibos_temp = {temp_dir}\recibos_temp.xlsx
# ==========================================================
# CSAG — TABELAS
# ==========================================================
csag_tabelas_dir = {gdrive_csag}\Tabelas
residentes_file = {csag_tabelas_dir}\Tabela_Residentes.xlsx
residentes_cc_file = {csag_tabelas_dir}\Residentes_cc.xlsx
# ==========================================================
# CSAG — PONTO
# ==========================================================
ponto_dir = {gdrive_csag}\Ponto
# ==========================================================
# ASSOCIADOS
# ==========================================================
associados_dir = {gdrive_associados}
associados_file = {associados_dir}\Ass_F3M.xlsx
saldos_file	= {associados_dir}\Quotas\F3M_Associados_saldos.xlsx
# ==========================================================
# APROVISIONAMENTO
# ==========================================================
aprovisionamento_dir = {gdrive_aprovisionamento}\aprovisionamento
aprovisionamento_file = {aprovisionamento_dir}\aprovisionamento.xlsx
fornecedores_file = {gdrive_aprovisionamento}\aprovisionamentoFornecedores.xlsx
pedidos_file = {gdrive_aprovisionamento}\aprovisionamentoPedidos.xlsx

[paths_templates]
pim_mensal_dir = {pim_dir}\{ano}\{mes}
csag_file = {pim_mensal_dir}\CSAG.xlsx
pdf_faturas = {pim_mensal_dir}\pdf_faturas.xlsx
faturacao_residentes = {pim_mensal_dir}\faturacao_residentes.xlsx
envio_faturas = {pim_mensal_dir}\envio_faturas.xlsx
pim_mensal_file = {pim_mensal_dir}\Pim.xlsx
diferencas_file = {pim_mensal_dir}\diferencas.xlsx


movimentos_do_dia = {secretaria_mov_dir}\movimentos_de_{ano}{mes}{dia}.xlsx

ponto_mensal_dir = {ponto_dir}\{ano}{mes}
ponto_mensal_file = {ponto_mensal_dir}\ponto_mensal.xlsx
ponto_diario_file = {ponto_mensal_dir}\ponto{mes}{dia}.xlsx

[users]
config_modo = jlagu; utilizador
banco = jlagu; utilizador; DELL; Jose Sousa; Virginia; Jose Faneco 
pim = jlagu; utilizador; DELL; Jose Sousa; Virginia
saldos = jlagu; utilizador; DELL; Jose Sousa
relatorios = jlagu; utilizador
aprovisionamento = jlagu; utilizador; jaimefontes
aprovisionamento_aut = jlagu; utilizador; jaimefontes
aprovisionamento_rel = jlagu; utilizador; jaimefontes
[aprovisionamento]
centros_custo = CSAG, Lar, Centro de dia, Assitencia domiciliaria, Sede, AlmadArte, Espaço Memória, Exposição, Clubes
[emails_direcao]
lista = jaimefontes@atrpt.pt,jlaguiarpinto@atrpt.pt,jamqueiroz@atrpt.pt,alvarespardal@atrpt.pt,anamlmagalhaes@atrpt.pt
[emails_sg]
lista = jlaguiarpinto@atrpt.pt
[emails_auth_pedidos]
lista = jlaguiar_pinto@atrpt.pt

[email.secretaria]
# Identidade
email_address = secretaria@atrpt.pt
# SMTP (envio)
smtp_server = smtp-pt.securemail.pro
smtp_port = 587
smtp_user = secretaria@atrpt.pt
smtp_password = Admin::2020::
smtp_starttls = true
smtp_debug = true
# IMAP (receção)
imap_server = mail-pt.securemail.pro
imap_port = 993
imap_user = secretaria@atrpt.pt
imap_password = Admin::2020::
imap_ssl = true
# Pastas a processar
imap_folders = INBOX, Faturas
[email.associados]
smtp_port = 587
smtp_user = associados@atrpt.pt
smtp_password = sky2020_new
smtp_server = smtp-pt.securemail.pro
smtp_debug = true
imap_server = mail-pt.securemail.pro
email_address = associados@atrpt.pt
imap_password = 
[email.aprovisionamento]
email_address = secretaria@atrpt.pt
smtp_server = smtp-pt.securemail.pro
smtp_port = 587
smtp_user = secretaria@atrpt.pt
smtp_password = Admin::2020::
smtp_starttls = true
smtp_debug = true
[email.geral]
smtp_port = 587
smtp_user = geral@atrpt.pt
smtp_password = 2022#atrpt
smtp_server = smtp-pt.securemail.pro
imap_server = mail-pt.securemail.pro
email_address = geral@atrpt.pt
imap_password = 
[email.lar]
smtp_port = 587
smtp_user = larsgabriel@atrpt.pt
smtp_password = gabriel#atrpt
smtp_server = smtp-pt.securemail.pro
imap_server = mail-pt.securemail.pro
email_address = larsgabriel@atrpt.pt
imap_password = 
[email.saude]
smtp_port = 587
smtp_user = csagsaude@atrpt.pt
smtp_password = saude#2023
smtp_server = smtp-pt.securemail.pro
imap_server = mail-pt.securemail.pro
email_address = csagsaude@atrpt.pt
imap_password = 




